### ISSUE TITLE
Erfordert, daß jQuery im Seitenlayout aktiviert ist 

### ISSUE THREAD

**Issue by fiedsch** [leycommediasolutions/contao-frontend-builder#1]
Das sollte vielleicht noch in der Doku erwähnt werden, sonst sieht man außer dem "Layoutbuilder-Balken" nichts und weiß erst mal nicht, warum.

**Comment by leycommediasolutions** [comment]
Danke für die Info, das haben wir in unserer README unter Wichtiges ergänzt. In der nächsten Version wird im Frontend ein Hinweis erscheinen.

**Comment by akroii** [comment]
Wieso bekomme ich trotz eingeschalteten jquery folgende Fehlermeldung?
<img width="675" alt="Bildschirmfoto 2020-09-23 um 20 46 02" src="https://user-images.githubusercontent.com/8830861/94055909-d7e61000-fddd-11ea-96df-54790419776f.png">

Wenn ich in der bundles/frontendbuilder/js/functions.js die erste Zeile mit 
`jQuery(function ($){`
ersetze geht es. 🤔
