### ISSUE TITLE
Blockieren von 1up-lab/contao-mailchimp

### ISSUE THREAD

**Issue by jankout** [leycommediasolutions/contao-frontend-builder#2]
Hallo, 

wenn Ihre Erweiterung aktiv ist, blockiert sie [folgende Erweiterung und verursacht folgenden Fehler](https://github.com/1up-lab/contao-mailchimp/issues/28).

**Comment by leycommediasolutions** [comment]
Hallo, 

eine neue Version ist nun verfügbar. In dieser Version sollte das Problem nicht mehr auftreten.
