### ISSUE TITLE
Debug Modus nicht nutzbar da Warnung

### ISSUE THREAD

**Issue by theDyingMountain** [leycommediasolutions/contao-frontend-builder#3]
Erstmal vielen Dank für die Supererweiterung.
Leider erhalte ich bei Nutzung des Debug Modus eine "Countable" Warnung:
`Warning: count(): Parameter must be an array or an object that implements Countable`
Zeile 435 in FrontendHooks.php

**Comment by leycommediasolutions** [comment]
Danke für den Hinweis. 
Wir haben für diese Erweiterung gerade eine neue Version freigeschaltet (1.0.4). Hier sollte dieses Problem nicht mehr auftreten.

**Comment by theDyingMountain** [comment]
Super danke fürs fixen 🙂
